### PR TITLE
Create spss_3.0_odpi_v1.0.1

### PR DESCRIPTION
**Pull request by jmertic**

### CODE REVIEW

**Comment by alanfgates** [comment]
I think it's just a copy paste error but question 'd' (which ODPi compliant distros did you test with?) isn't answered.

**Review by sumalaika — COMMENTED** [review]
yes - sorry about omission. Tested with IOP 4.2 and HDP 2.4.2

**Comment by jmertic** [comment]
Thanks @sumalaika !

@alanfgates I updated the doc - please review and merge if acceptable.

**Comment by rvs** [comment]
LGTM. @alanfgates lets merge so we have no outstanding PRs for the release today.

**Pull request merged**
