### PR TITLE
Pivotal's self certification of Pivotal HDB for ODPi Runtime Interoperability

### PR DESCRIPTION
**Pull request by GregChase**

### CODE REVIEW

**Comment by alanfgates** [comment]
One question, which release of HDP 2.4 did you use?  Only HDP 2.4.2 is certified against ODPi.

**Comment by GregChase** [comment]
We used 2.4.2.  I truncated to 2.4 when I saw SAS was using the same.

**Comment by alanfgates** [comment]
Ok, can I ask you to change it to 2.4.2 and then I'll merge it.  I thought I had SAS do that too.  Oops.

**Comment by GregChase** [comment]
Done

**Pull request merged**
